language: node_js
node_js:
- '0.10'
sudo: false
env:
  global:
  - envName=travis
before_script:
- mysql -e "create database twilioDbTest;"
after_success:
- istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat
  ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
- npm run report-coverage
